server:
  port: 8080
spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:43ahegib}
    url: jdbc:postgresql://${SWEATER_DATABASE_HOST:localhost}:${SWEATER_DATABASE_PORT:5432}/${SWEATER_DATABASE_NAME:sweater}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  freemarker:
    expose-request-attributes: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_NAME:mynodetester@gmail.com}
    password: ${MAIL_PASSWORD:yfdseqbtrixcxlls}
    properties:
      mail:
        transport:
          protocol: ${TRANSPORT_PROTOCOL:smtp}
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS_ENABLE:true}
    protocol: ${PROTOCOL:smtp}
    default-encoding: UTF-8
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:postgresql://${AUTH_DATABASE_HOST:localhost}:${AUTH_DATABASE_PORT:5432}/${AUTH_DATABASE_NAME:sweater}?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectionCollation=utf8_general_ci&amp;characterSetResults=UTF-8
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:43ahegib}
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION


upload:
  path: ${UPLOAD_PATH:/C:\Users\Admin\Desktop\sweater\Files}

recaptcha:
  secret: 6LfERr4hAAAAAKEGwD1RnQWYelJ7aalHc6lZI_T0
